SELECT
    `idAsesmenAwalTriage`
    , `noRekamedis`
    , `noDaftar`
    , `noDaftarUnit`
    , `tglDaftarUnit`
    , `diKrimOleh`
    , `namaPengirim`
    , `alamatPengirim`
    , `diagnosaRujukan`
    , `terapiYangDiberikan`
    , `tglMasuk`
    , `jamMasuk`
    , `nonTrauma`
    , `obsterti`
    , `trauma`
    , `tglTrauma`
    , `jamTrauma`
    , `lokasiTkp`
    , `caraDatang`
    , `keluhanUtama`
    , `riwayatSingkat`
    , `keadaanUmum`
    , `kesadaran`
    , `jalanNafasResutassiSumbatan`
    , `jalanNafasEmergencyBebas`
    , `jalanNafasUrgentBebas`
    , `jalanNafasNonUrgentBebas`
    , `jalasNafasFalseEmergencyBebas`
    , `pernafasanResutasiHentiNafas`
    , `pernafasanResutasiPR1Menit`
    , `pernafasanResutasiPR40Menit`
    , `pernafasanResutasiSiagnosiSentral`
    , `pernafasanResutasiSiagnosi`
    , `pernafasanResutasiApnea`
    , `pernafasanEmergencyPR`
    , `pernafasanEmergencyWheezing`
    , `pernafasanEmergencyPr80`
    , `pernafasanEmergencySianosis`
    , `pernafasanTandaVitalSa02`
    , `pernafasanTandaVitalFrekNafas`
    , `pernafasanUrgentPr24`
    , `pernafasanUrgentWheezing`
    , `pernafasanUrgentPr60`
    , `pernafasanUrgentSianosi`
    , `pernafasanNonUrgentNormal`
    , `pernafasanFalseEmergencyNormal`
    , `sirkulasiResutasiHenditkanJantung`
    , `sirkulasiResutasiNadiTidakTerabahLemah`
    , `sirkulasiResutasiPucatPale`
    , `sirkulasiResutasiAkralDingin`
    , `sirkulasiResutasiFrek`
    , `sirkulasiResutasiCrt`
    , `sirkulasiEmergencyNadiTerabaLemah`
    , `sirkulasiEmergencyBraadikardia`
    , `sirkulasiEmergencyTachikardia`
    , `sirkulasiEmergencyPucat`
    , `sirkulasiEmergencyAkiralDingin`
    , `sirkulasiEmergencyFrekNadi`
    , `sirkulasiEmergencyCrt`
    , `sirkulasiTandaVitalTekananDarah`
    , `sirkulasiTandaVitalNadi`
    , `sirkulasiUrgentNadiTeraba`
    , `sirkulasiUrgentFrekNadi`
    , `sirkulasiUrgentTekDarahSistole`
    , `sirkulasiUrgentTekDarahDiastole`
    , `sirkulasiUrgentCrt`
    , `sirkulasiNonUrgentNormal`
    , `sirkulasiFalseEmergencyNormal`
    , `kesadaranResutasiGcs`
    , `kesadaranResutasiNeonatus`
    , `kesadaranEmergencyGcs`
    , `kesadaranEmergencyNeonatus`
    , `kesadaranTandaVitalE`
    , `kesadaranTandaVitalV`
    , `kesadaranTandaVitalM`
    , `kesadaranTandaVitalSuhu`
    , `kesadaranUrgentGcs`
    , `kesadaranNonUrgentGcs`
    , `kesadaranNonUrgentLuka`
    , `kesadaranNonUrgentTrauma`
    , `kesadaranNonUrgent36`
    , `kesadaranFalseEmergencyNormal`
    , `kesadaranFalseEmergencyLuka`
    , `kesadaranFalseEmergency36`
FROM
    `t_asesmen_awal_triage`;